### ISSUE TITLE
Implement the connector modal UI [React, TS, Starknet.js]

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA-SDK#22]
1. When a call to the connector is made, the modal pops up with an input box to input TBA address, and a select dropdown to select what wallet the parent account (argentX, braavos, argentWebWallet, argentMobile).
2. The modal instantiates `TokenboundConnector` with the TBA address and parent account ID. e.g
```js
import { TokenboundConnector } from "tokenbound-connector"
  const tokenbound = new TokenboundConnector({
      tokenboundAddress: "0x3ab349247d8a1317cbb3b2d503fc50a6fd2748856a141c6379aea34b0f602f3",
      parentAccountId: "argentX"
  })
```
3. Finally the modal returns the instantiated `tokenbound` which users/dapps can use.

This should be created with modularity in mind, so when we add to Starknetkit, we should be able to call this modal from a click of a button.

<img width="595" alt="Screenshot 2024-02-15 at 14 10 39" src="https://github.com/Starknet-Africa-Edu/TBA-SDK/assets/75126961/17173ccf-aae5-4b6c-93b9-f1bbba2d276a">

**Comment by codeWhizperer** [comment]
@Darlington02  is this issue still open?

**Comment by codeWhizperer** [comment]
@Darlington02 is the issue still open, and what needs to be done?

**Comment by Darlington02** [comment]
Yes, it is. And there's quite a lot to be done. Let's discuss on a call

**Comment by ktarun1419** [comment]
@Darlington02  Can i also work on this issue?
