### ISSUE TITLE
Connector SDK Readme and docs

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA-SDK#32]
Once connector has been successfully integrated in starknetkit, write a detailed readme in the `connector` folder and add a section for Tokenbound Connector in the [Starknetkit docs](https://www.starknetkit.com/docs/connectors/connectors) and the main [starknet tokenbound docs](https://tokenbound.gitbook.io/starknet-tokenbound/sdk)

**Comment by Nonnyjoe** [comment]
I'll love to handle this

**Comment by kenkomu** [comment]
@Darlington02  can I take this?
